services:
    mysql:
        build:
            context: .
            dockerfile: docker/mysql/Dockerfile
        environment:
            MYSQL_DATABASE: news
            MYSQL_ROOT_USERNAME: root
            MYSQL_ROOT_PASSWORD: root
        networks:
            - net

    phpmyadmin:
        image: phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: root
            PMA_ARBITRARY: 1
            PMA_ABSOLUTE_URI: http://localhost/phpmyadmin
        networks:
            - net
        depends_on:
            - mysql

    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        environment:
            - DB_HOST=mysql
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html
        networks:
            - net
        depends_on:
            - mysql

networks:
    net:
        driver: bridge